spring.application.name=construxflow

spring.datasource.url=jdbc:postgresql://localhost:5432/construxflow
spring.datasource.username=postgres
spring.datasource.password=ashan1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

